apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-seed-data
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed-data
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -U postgres; do
                echo "Waiting for postgres..."
                sleep 2
              done

              psql -h postgres -U postgres -d schooldb -f /scripts/init.sql
          env:
            - name: PGPASSWORD
              value: {{.Values.postgres.postgresDbPass}}
          volumeMounts:
            - name: init-script
              mountPath: /scripts
      volumes:
        - name: init-script
          configMap:
            name: postgres-init-script