apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: management
      protocol: TCP
      name: management

  selector:
    app: keycloak

---

apiVersion: v1
kind: Service
metadata:
  name: students
spec:
  type: {{ .Values.students.service.type }}
  ports:
    - port: {{ .Values.students.service.port }}
      targetPort: {{ .Values.students.service.port }}
      protocol: TCP
      name: http
  selector:
    app: students

---

apiVersion: v1
kind: Service
metadata:
  name: library
spec:
  type: {{ .Values.library.service.type }}
  ports:
    - port: {{ .Values.library.service.port }}
      targetPort: {{ .Values.library.service.port }}
      protocol: TCP
      name: http
  selector:
    app: library

---

apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  type: {{ .Values.apigateway.service.type }}
  ports:
    - port: {{ .Values.apigateway.service.port }}
      targetPort: {{ .Values.apigateway.service.port }}
      protocol: TCP
      name: http
  selector:
    app: apigateway

---
apiVersion: v1
kind: Service
metadata:
  name: course
spec:
  type: {{ .Values.course.service.type }}
  ports:
    - port: {{ .Values.course.service.port }}
      targetPort: {{ .Values.course.service.port }}
      protocol: TCP
      name: http

    - port: 9090
      targetPort: 9090
      name: grpc
      protocol: TCP

  selector:
    app: course

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: exam
spec:
  type: {{ .Values.exam.service.type }}
  ports:
    - port: {{ .Values.exam.service.port }}
      targetPort: {{ .Values.exam.service.port }}
      protocol: TCP
      name: http

    - port: 9090
      targetPort: 9090
      name: grpc
      protocol: TCP

  selector:
    app: exam